drawing:
  current_tool: brush
  tool_settings:
    adjust: {}
    brush:
      Color: '#000000'
      Line Style: solid
      Opacity: '100'
      Size: '5'
      color: '#00ff00'
      line_style: dot
      opacity: '100'
      size: '36'
    eraser:
      Size: '20'
      size: '75'
    move: {}
    pen:
      Color: '#000000'
      Size: '8'
      color: '#00ffff'
      size: '13'
    select: {}
    shape:
      Line Style: solid
      Shape: rectangle
      Stroke Color: '#000000'
      Stroke Size: '2'
      line_style: solid
      shape: rectangle
      stroke_color: '#000000'
      stroke_size: '2'
    text:
      Font Size: '14'
      Text Color: '#000000'
      font_size: '14'
      text_color: '#000000'
    zoom: {}
task_index: 1
timeline_duration: 20.125
timeline_index: 10
timeline_item_durations:
  '1': 1.0
  '10': 6.0625
  '2': 1.0
  '3': 1.0
  '4': 1.0
  '5': 1.0
  '6': 1.0
  '7': 1.0
  '8': 1.0
  '9': 6.0625
timeline_position: 16.368
timeline_size: 8
