"""Global constants for Filmeto application."""

# File extensions
YAML_EXTENSION = ".yml"
YAML_GLOB_PATTERN = "*.yml"

# Common file names
PROJECT_CONFIG_FILE = f"project{YAML_EXTENSION}"
SETTINGS_FILE = f"settings{YAML_EXTENSION}"
SETTINGS_TEMPLATE_FILE = f"settings_template{YAML_EXTENSION}"
PLUGIN_CONFIG_FILE = f"plugin{YAML_EXTENSION}"
CONVERSATIONS_INDEX_FILE = f"conversations_index{YAML_EXTENSION}"
RESOURCE_INDEX_FILE = f"resource_index{YAML_EXTENSION}"
TASK_CONFIG_FILE = f"config{YAML_EXTENSION}"
TIMELINE_CONFIG_FILE = f"config{YAML_EXTENSION}"
CHARACTER_CONFIG_FILE = f"config{YAML_EXTENSION}"
PLAN_FILE = f"plan{YAML_EXTENSION}"
PLAN_INSTANCE_FILE = f"plan_instance{YAML_EXTENSION}"
SERVER_CONFIG_FILE = f"server{YAML_EXTENSION}"
ROUTER_CONFIG_FILE = f"server_router{YAML_EXTENSION}"
TEMPLATE_FILE_PATTERN = f"template_*{YAML_EXTENSION}"